server:
  port: 8080
cors:
  originPatterns: http://localhost:3000,http://localhost,http://localhost:8080,http://3.144.168.192,http://harnonn.com
file: 
  upload-dir: C:/Users/harno/Documents/files
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000 
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    open-in-view: true
  servlet:
   multipart:
     enabled: true
     file-size-threshold: 2KB
     max-file-size: 200MB
     max-request-size: 215MB
springdoc:
  paths-to-match:
    - /auth/** 
    - /api/**/v1/**
  swagger-ui: 
    use-root-path: true